version: '2'
services:
  app:
    build: .
    image: miloofcroton/simple-go:1.0.3
    environment:
      - PORT=9090
    ports:
      - "9090:9090"
  nginx:
    image: "nginx:1.11.9"
    ports:
      - "8080:80"
    links:
      - app
